server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: spStuMan
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/spstuman"
    username: lahm
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info